server {
    listen 80;
    server_name messages.egliseemec.org;

    root /home/projects/emec-projects/dosc-emec/dist;
    index index.html;

    access_log /var/log/nginx/messages.egliseemec.org.access.log;
    error_log /var/log/nginx/messages.egliseemec.org.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
